### PR TITLE
Add thephilosopherD

### PR DESCRIPTION
**Pull request by thephilosopherD**
thephilosopherD

### CODE REVIEW

**Comment by thephilosopherD** [comment]
Add me!

**Comment by thephilosopherD** [comment]
Let's try again.

**Comment by jlord** [comment]
Sorry about the delay! I wrote a :bug: in @reporobot yesterday—but he's better now :grin:

**Comment by thephilosopherD** [comment]
Hi Jessica, thank you for the help and the fix. Love the tutorial!

-Daniel

**Pull request closed without merging**
