### PR TITLE
Fixed a mistake

### PR DESCRIPTION
**Pull request by mironouz**
Fixed a small mistake on main page
@jlord

### CODE REVIEW

**Comment by jlord** [comment]
Thanks! ✨  Do you think you could make the change so it only updates that word and not the ascii text?  

The template used to generate this page is in a different repo and I've updated it there → https://github.com/jlord/reporobot/commit/64e66d42f4e16348fea1aa8bd738a084620285c4

**Comment by mironouz** [comment]
@jlord, I have fixed it for now, but your tutorial is very popular and it could be changed in every moment=)

**Comment by jlord** [comment]
Thanks! Actually it will probably go back to the misspelled version as soon as the next person gets added here because I haven't updated the server yet (and can't until a little later) 😬

**Comment by mironouz** [comment]
You are welcome! Yeah, it makes sense. I didn't know about template, anyway we fixed it!

**Pull request merged**
