### PR TITLE
Removed this file, which due to its conflict with contributors/add-p1xt....

### PR DESCRIPTION
**Pull request by airportyh**
...txt which is a file with the same name but different casing of the letter P, causes both Windows and Mac users to see a modified status on this file immediately upon cloning the repository.

### CODE REVIEW

**Comment by airportyh** [comment]
@jlord: I am teaching a workshop and this is problem is consistently showing up and has been confusing for the students.

**Comment by jdennes** [comment]
:+1: We just had people experience the same issue at [Ruby Monstas](http://rubymonstas.org/).

/cc @fooforge @svenfuchs

**Comment by jlord** [comment]
Hiya! Sorry for the delay, was on an airplane and such for a while. Thanks for this PR! :sparkles: 

Happy to merge! Also, if anyone is using Git-it more than once or something and wants to be added to this repo, I'm happy to add!

**Comment by airportyh** [comment]
Thanks!

**Pull request merged**
