### PR TITLE
Reinsert usernames into GitHub links

### PR DESCRIPTION
**Pull request by gjtorikian**
ohai!

@jlord, I noticed that the index page of http://jlord.us/patchwork/ has stopped adding usernames to the link to people's profiles. This PR adds back the username for anyone missing it.

This doesn't fix the underlying problem of properly rewriting the index, though. I am not sure where to go about doing that; seems like a @reporobot problem, but I can't find the code where s/he does the rewrite.

### CODE REVIEW

**Comment by gjtorikian** [comment]
The file's too big for GitHub to show. :disappointed: 

Check out this line: https://github.com/gjtorikian/patchwork/blob/c0b30ef2565bb28ad7d576adb1ca77c7136f7649/index.html#L39

Compared to the current line: https://github.com/jlord/patchwork/blob/17e7a659e91b338c7aa73ff9cb215d97fece0661/index.html#L39

The `a` URL just ends with `www.github.com/`.

**Comment by jlord** [comment]
Oh, yikes! Thanks so much @gjtorikian! 

I think that's a problem in @reporobot's template here: https://github.com/jlord/reporobot/blob/master/template.hbs#L28... I seem to remember at some point I started using the variable `user` instead of `username` and actually need to include both/clean up all that and just use one. 

Also, lol @reporobot responding to all PRs! Good job @reporobot!

**Comment by gjtorikian** [comment]
> Also, lol @reporobot responding to all PRs! Good job @reporobot!

**Comment by jlord** [comment]
Bandaid until I fix the larger issue: https://github.com/jlord/reporobot/commit/2baa1ad914a4d6b23af10b001018c2b54ebbc1cb

**Pull request merged**
